name: Compile CV and Upload to Google Drive

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache LaTeX packages
      - name: Cache TeX Live
        uses: actions/cache@v4
        with:
          path: |
            ~/.texlive
            /usr/local/texlive
          key: texlive-${{ runner.os }}-v1

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            texlive-xetex \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            latexmk

      - name: Compile PDF
        working-directory: cv_khalil_ben_romdhane/junior_developer_template
        run: |
          latexmk -xelatex -interaction=nonstopmode main.tex

      - name: Move PDF to root
        run: |
          mv cv_khalil_ben_romdhane/junior_developer_template/main.pdf \
             CV_BenRomdhane_Khalil_${{ github.event.release.tag_name }}.pdf

      - name: Debug files
        run: ls -lah

      - name: Upload PDF to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: CV_BenRomdhane_Khalil_${{ github.event.release.tag_name }}.pdf

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          name: CV_BenRomdhane_Khalil_${{ github.event.release.tag_name }}.pdf
          overwrite: true